### ISSUE TITLE
Update for Docker 1.9 Volume API

### ISSUE THREAD

**Issue by porcupie** [yp-engineering/rbd-docker-plugin#13]
The Docker 1.9 Volume API now has a hashmap of Options passed on Create.  Implement this for Ceph and provide some standard options for creating Ceph volumes (Size, Pool, Filesystem, etc).
- http://docs.docker.com/engine/extend/plugins_volume/

**Comment by hekaldama** [comment]
@porcupie is this still needed? Does #21 relate to this?

**Comment by porcupie** [comment]
@hekaldama Yes still needed - and #21 is also needed as we are now 2 versions of Docker API behind for the Volume Plugin API changes.

I think we should use the new plugins helper too instead of dkvolume and I we may get some of this for free:
- https://github.com/docker/go-plugins-helpers

**Comment by a-nldisr** [comment]
I suspect this is related to docker volume api 1.9 changes (this is why i place it here), but your el7 build process is building against docker sockets. They have been removed since latest release, error i get:
imports github.com/docker/docker/pkg/sockets: cannot find package "github.com/docker/docker/pkg/sockets" in any of... 

More people running into this: 
https://github.com/calavera/docker-volume-keywhiz/issues/1
and 
https://github.com/gondor/docker-volume-netshare/issues/6

**Comment by hekaldama** [comment]
@a-nldisr I am unsure if this is still an issue. Can you reopen if it is with anymore info that we may need. Thanks.
